[package]
name = "fourier-svg"
version = "0.1.0"
authors = ["Inoki <veyx.shaw@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustfft = "6.0"
lyon = "0.17"
lyon_path = "0.17"
lyon_svg = "0.17"
